### ISSUE TITLE
Change every boolean typed column to smallint

### ISSUE THREAD

**Issue by GaborFarkas** [DateliteLtd/UserSpice5OnPostgres#3]
And make sure there is no incompatibility with the code where they are used.

**Comment by ssobii2** [comment]
Ok i will test every code in pgadmin manually and also the update files code

**Comment by ssobii2** [comment]
Also i was having issues with git push after editing commits so thats why index.php is pushed again. I untracked the file now after fixing the issue. I had other issues too one was about no upstream which idk what it means. I think now i will just clone the branch again and start fresh and will untrack the files again. This should solve many issues i think.
