### ISSUE TITLE
Fix installer

### ISSUE THREAD

**Issue by GaborFarkas** [DateliteLtd/UserSpice5OnPostgres#5]
Please fix the installer files to work with PostgreSQL in a fully compatible way:

- Pre-installation checks should work
- Connection testing should work (not necessarily with the current MySQL way of creating a new DB + user, if there is a simpler way)
- Automatic DB creation should work on missing DB, if possible in PostgreSQL
- Automatic execution of `sql.sql` should work (not necessarily with the current MySQL way of executing it line by line, IF PostgreSQL is capable of executing a full SQL file and returning the problematic line on error)

**Comment by ssobii2** [comment]
First, I will try to make it work as it worked with MYSQL then we will see if changes are required

**Comment by ssobii2** [comment]
Please check my email professor when free
